# Homework

### Problem 1
- Write a function `dot_product` to calculate the dot product of two 1 by n arrays. For example:
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [3]:
#### Your code here
import numpy as np
import scipy 

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

def dot_product(a,b):
    if len(a)==len(b):
        return a.dot(b)
    else:
        raise Exception("Arrays must be of equal length.")
    

In [4]:
#### Test

import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,5])
print(dot_product(a, b))


65


- Given a 1 by n array `a`, write a function `odd(a)` to return a new array containing elements whose index is an odd number.

```
a = np.array([1, 3, 4, 2, 5, 3, 8, 1])
odd(a) = array([3, 2, 3, 1])
```

In [84]:

#### Test
a = np.array([1, 3, 4, 2, 5, 3, 8, 1])
b = a[1::2]
b

array([3, 2, 3, 1])

### Problem 2
Construct the following arrays without listing all the elements. For example, you should use **np.ones(3)** to generate a array *array([1, 1, 1])* instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [49]:
import numpy as np
x = np.arange(11.0)
x

#### Your code here

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [59]:
#### Your code here
x = np.arange(11.0)
y = np.arange(0,23,3.3)
y

array([ 0. ,  3.3,  6.6,  9.9, 13.2, 16.5, 19.8])

(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [4]:
#### Your code here
import numpy as np
print(np.linspace(0,23,7))


[ 0.          3.83333333  7.66666667 11.5        15.33333333 19.16666667
 23.        ]


(4) Create a 5x5 matrix with row values ranging from 0 to 4.

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [86]:
#### Your code here
x = np.arange(11.0)
y = np.arange(0,23,3.3)
z = np.arange(0,9).reshape(3,3)

a = np.ones((25)).reshape(5,5)
b = np.arange(0,5)

print(a*b)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


(5) A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)


In [429]:
### Your code here  
def isMagic(square):
    shape = square.shape
    if shape[0]==shape[1]:
        sorted_square = np.sort(square, axis = None)
        sorted_test   = np.arange(1,((shape[0])**2)+1)
        if np.array_equal(sorted_square,sorted_test) and sum(np.diag(np.fliplr(square)))== sum(np.diag(square)) and \
        sum(np.diag(square)) == np.sum(square[0]):
            for n in range(shape[0]):
                if np.sum(square[n], axis=0) != np.sum(square[n]):
                    return 'Not Magic!'
            return 'Magic!'
        else:
            return 'Not Magic!'
    else:
        return 'Not Magic!'



Here are some tests:

In [431]:
test1 = np.array([[0, 1], 
                  [1, 0]])
isMagic(test1) # False

'Not Magic!'

In [430]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True

'Magic!'

In [432]:
test3 = np.array([[2, 6, 7],
                  [4, 8, 3],
                  [9, 1, 5]])


isMagic(test3) # False

'Not Magic!'

In [418]:
test4 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test4) # True

'Magic!'

In [419]:
test5 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test5) # True

'Magic!'

In [420]:
test6 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
#np.sort(test6, axis = None).reshape(test6.shape)
isMagic(test6) # True

'Magic!'

### Problem 3


We discuss random sampling in the class, which helps when exact solution is hard to obtain. For example, we know that the area of a circle is $\pi \times r^2 \text{, where } r \text{ is the radius of the circle. }$ But we don't know how to approximate the number $\pi$.

Monte Carlo simulation can help.

<img src=https://s3.amazonaws.com/nycdsabt01/monte_carlo.png width=330/>

- Use `np.random.uniform` function to generate 2000 two dimensional samples. `uniform` indicates that the likelihood for any number from **-1 to 1** occurs is uniform. The shape of your sample should look like below (of course the actual numbers can be different)
```
array([[-0.53277773, -0.93122476],
        [ 0.16017788, -0.74177143],
        [ 0.37248292,  0.36734988],
        ..., 
        [ 0.5314644 , -0.50411338],
        [ 0.12208452,  0.6242463 ],
        [ 0.74767075, -0.56486567]])
```
Therefore all the samples fall in the $[-1, 1] \times [-1, 1] \text{ box.}$

In [8]:
import numpy as np
import math
rand = np.random.uniform(-1,1,4000).reshape(2000,2)
#area = rand.reshape(2000,2)
rand.shape

(2000, 2)

- The probability of points being in the circle is the ratio between the area of the circle and the area of the $[-1, 1] \times [-1, 1] \text{ box.}$ More precisely,

$$\text{Probability} \big( \text{points falling in the circle} \big) = \frac{\text{area of the circle}}{\text{area of the rectangle}} = \frac{\pi}{4},$$

From the sample you generate in the last problem, estimate the probability of falling in the circle, then approximate $\pi$.

In [290]:
(math.pi/4)

0.7853981633974483

In [355]:
import numpy as np
import math
rand = np.random.uniform(-1,1,4000)
area = rand.reshape(2000,2)
circ = 0



for n in area:
    if (n[0]**2)+(n[1]**2) <= 1:
        circ = circ +1        
prob = (circ/2000)
piie = prob*4
piie


#probability = np.mean(pts[:,0]**2 + pts[:,1]**2 <=1)
#probability*4 


In [356]:

piie

3.152